[package]
name = "docs"
version = "0.1.0"
edition = "2024"
description = "A sample package for crate and documentation functionality"
license = "MIT OR Apache-2.0"


[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3


[dependencies]
